create table thistusuar(
    /*table of the users*/
	cedul_usuar varchar(12) primary key,
	nomb_usuar varchar(30) not null,
	telef_usuar varchar(12) not null,
    pass_usuar text not null,
    rol_usuar varchar(20),
    token_usuar text
)

create table thisproveed(
    /*table of the company*/
	cod_proveed integer primary key generated by default as identity,
	nombre_proveed varchar(30) not null,
	descrip_proveed text not null,
	fechcompr_proveed date not null
)