--
-- PostgreSQL database dump
--

-- Dumped from database version 12.8
-- Dumped by pg_dump version 12.8

-- Started on 2021-10-01 10:35:37

--
-- TOC entry 216 (class 1259 OID 24768)
-- Name: thistcomponentred; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thistcomponentred (
    cod_componentred integer NOT NULL,
    macaddress_componentred text NOT NULL,
    ipaddress_componentred text NOT NULL,
    observ_componentred text
);

--
-- TOC entry 215 (class 1259 OID 24766)
-- Name: thistcomponentred_cod_componentred_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.thistcomponentred ALTER COLUMN cod_componentred ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thistcomponentred_cod_componentred_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 24751)
-- Name: thistctrolcompred; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thistctrolcompred (
    cod_compred integer NOT NULL,
    macadress_compred text,
    ipadress_compred text,
    pkcod_departament integer
);


--
-- TOC entry 213 (class 1259 OID 24749)
-- Name: thistctrolcompred_cod_compred_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.thistctrolcompred ALTER COLUMN cod_compred ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thistctrolcompred_cod_compred_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 24678)
-- Name: thistctrolequipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thistctrolequipo (
    cod_equipo integer NOT NULL,
    descrip_equipo text NOT NULL,
    fechactrol_equipo date NOT NULL,
    firma_equipo text NOT NULL,
    pfced_usuario character varying(15),
    pfcod_departament integer
);


--
-- TOC entry 207 (class 1259 OID 24676)
-- Name: thistequipo_cod_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.thistctrolequipo ALTER COLUMN cod_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thistequipo_cod_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 24648)
-- Name: thistproveed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thistproveed (
    cod_proveed integer NOT NULL,
    nombre_proveed character varying(30) NOT NULL,
    descrip_proveed text NOT NULL,
    fechadquis_proveed date NOT NULL
);



--
-- TOC entry 203 (class 1259 OID 24646)
-- Name: thistproveed_cod_proveed_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.thistproveed ALTER COLUMN cod_proveed ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thistproveed_cod_proveed_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 24656)
-- Name: tmaecomponent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tmaecomponent (
    cod_component integer NOT NULL,
    nombre_component character varying(30) NOT NULL,
    descrip_component text NOT NULL,
    marca_component character varying(20) NOT NULL,
    model_component character varying(25) NOT NULL,
    numerser_component character varying(25) NOT NULL,
    pfcod_proveed integer,
    pfcod_equipo integer,
    pfcod_componentred integer,
    fechverf_component date
);


--
-- TOC entry 206 (class 1259 OID 24661)
-- Name: tmaecomponent_cod_component_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tmaecomponent ALTER COLUMN cod_component ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tmaecomponent_cod_component_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 24731)
-- Name: tmaedepartament; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tmaedepartament (
    cod_departament integer NOT NULL,
    nomb_departament character varying(25) NOT NULL,
    descrip_departament text NOT NULL,
    pfcod_componentred integer
);


--
-- TOC entry 211 (class 1259 OID 24729)
-- Name: tmaedepartament_cod_departament_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tmaedepartament ALTER COLUMN cod_departament ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmaedepartament_cod_departament_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 24711)
-- Name: tmaesoft; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tmaesoft (
    cod_softw integer NOT NULL,
    nomb_soft character varying(25) NOT NULL,
    descrip_soft text NOT NULL,
    licencia_soft text NOT NULL,
    pfcod_proveed integer,
    pfcod_equipo integer
);



--
-- TOC entry 209 (class 1259 OID 24709)
-- Name: tmaesoft_cod_softw_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tmaesoft ALTER COLUMN cod_softw ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmaesoft_cod_softw_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 24605)
-- Name: tmaeusuar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tmaeusuar (
    cedul_usuar character varying(15) NOT NULL,
    nomb_usuar character varying(30) NOT NULL,
    telef_usuar character varying(12) NOT NULL,
    token_usuar text,
    pass_usuar text NOT NULL,
    rol_usuar character varying(20),
    pfcod_departament integer
);



--
-- TOC entry 2748 (class 2606 OID 24758)
-- Name: thistctrolcompred pk_thistctrolcompred_cod_compred; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistctrolcompred
    ADD CONSTRAINT pk_thistctrolcompred_cod_compred PRIMARY KEY (cod_compred);


--
-- TOC entry 2752 (class 2606 OID 24775)
-- Name: thistcomponentred pk_thistdepartament_cod_departament; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistcomponentred
    ADD CONSTRAINT pk_thistdepartament_cod_departament PRIMARY KEY (cod_componentred);


--
-- TOC entry 2742 (class 2606 OID 24682)
-- Name: thistctrolequipo pk_thistequipo_cod_equipo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistctrolequipo
    ADD CONSTRAINT pk_thistequipo_cod_equipo PRIMARY KEY (cod_equipo);


--
-- TOC entry 2740 (class 2606 OID 24660)
-- Name: tmaecomponent pk_tmaecomponent_cod_component; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaecomponent
    ADD CONSTRAINT pk_tmaecomponent_cod_component PRIMARY KEY (cod_component);


--
-- TOC entry 2746 (class 2606 OID 24735)
-- Name: tmaedepartament pk_tmaedepartament_cod_departament; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaedepartament
    ADD CONSTRAINT pk_tmaedepartament_cod_departament PRIMARY KEY (cod_departament);


--
-- TOC entry 2744 (class 2606 OID 24718)
-- Name: tmaesoft pk_tmaesoft_cod_softw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaesoft
    ADD CONSTRAINT pk_tmaesoft_cod_softw PRIMARY KEY (cod_softw);


--
-- TOC entry 2738 (class 2606 OID 24655)
-- Name: thistproveed thistproveed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistproveed
    ADD CONSTRAINT thistproveed_pkey PRIMARY KEY (cod_proveed);


--
-- TOC entry 2736 (class 2606 OID 24698)
-- Name: tmaeusuar thistusuar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaeusuar
    ADD CONSTRAINT thistusuar_pkey PRIMARY KEY (cedul_usuar);


--
-- TOC entry 2750 (class 2606 OID 24760)
-- Name: thistctrolcompred unq_thistctrolcompred_pkcod_departament; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistctrolcompred
    ADD CONSTRAINT unq_thistctrolcompred_pkcod_departament UNIQUE (pkcod_departament);


--
-- TOC entry 2758 (class 2606 OID 24736)
-- Name: thistctrolequipo fk_thistequipo_tmaedepartament; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistctrolequipo
    ADD CONSTRAINT fk_thistequipo_tmaedepartament FOREIGN KEY (pfcod_departament) REFERENCES public.tmaedepartament(cod_departament);


--
-- TOC entry 2757 (class 2606 OID 24704)
-- Name: thistctrolequipo fk_thistequipo_tmaeusuar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thistctrolequipo
    ADD CONSTRAINT fk_thistequipo_tmaeusuar FOREIGN KEY (pfced_usuario) REFERENCES public.tmaeusuar(cedul_usuar);


--
-- TOC entry 2756 (class 2606 OID 24776)
-- Name: tmaecomponent fk_tmaecomponent; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaecomponent
    ADD CONSTRAINT fk_tmaecomponent FOREIGN KEY (pfcod_componentred) REFERENCES public.thistcomponentred(cod_componentred);


--
-- TOC entry 2755 (class 2606 OID 24684)
-- Name: tmaecomponent fk_tmaecomponent_thistequipo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaecomponent
    ADD CONSTRAINT fk_tmaecomponent_thistequipo FOREIGN KEY (pfcod_equipo) REFERENCES public.thistctrolequipo(cod_equipo);


--
-- TOC entry 2761 (class 2606 OID 24781)
-- Name: tmaedepartament fk_tmaedepartament; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaedepartament
    ADD CONSTRAINT fk_tmaedepartament FOREIGN KEY (pfcod_componentred) REFERENCES public.thistcomponentred(cod_componentred);


--
-- TOC entry 2760 (class 2606 OID 24974)
-- Name: tmaesoft fk_tmaesoft_thistctrolequipo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaesoft
    ADD CONSTRAINT fk_tmaesoft_thistctrolequipo FOREIGN KEY (pfcod_equipo) REFERENCES public.thistctrolequipo(cod_equipo);


--
-- TOC entry 2759 (class 2606 OID 24719)
-- Name: tmaesoft fk_tmaesoft_thistproveed; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaesoft
    ADD CONSTRAINT fk_tmaesoft_thistproveed FOREIGN KEY (pfcod_proveed) REFERENCES public.thistproveed(cod_proveed);


--
-- TOC entry 2753 (class 2606 OID 24744)
-- Name: tmaeusuar fk_tmaeusuar_tmaedepartament; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaeusuar
    ADD CONSTRAINT fk_tmaeusuar_tmaedepartament FOREIGN KEY (pfcod_departament) REFERENCES public.tmaedepartament(cod_departament);


--
-- TOC entry 2754 (class 2606 OID 24671)
-- Name: tmaecomponent tmaecomponent_pkcodproveed_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tmaecomponent
    ADD CONSTRAINT tmaecomponent_pkcodproveed_fkey FOREIGN KEY (pfcod_proveed) REFERENCES public.thistproveed(cod_proveed);


-- Completed on 2021-10-01 10:35:41

--
-- PostgreSQL database dump complete
--

